# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1600"
    vb.cpus = 1
    vb.name = "estoffelS"
  end
  config.vm.define "estoffelS" do |server|
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "estoffelS"

    server.vm.provision "file", source: "confs", destination: "~/confs"
    server.vm.provision "shell", path: "scripts/k3s.sh"
  end
end
