# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end
  config.vm.synced_folder "./shared", "/vagrant_shared", create: true

  #Superviser VM
  config.vm.define "estoffelS" do |server|
    server.vm.network "private_network", type: "static", ip: "192.168.56.110"
    server.vm.hostname = "estoffelS"
    server.vm.provision "shell", path: "scripts/common.sh"
    server.vm.provision "shell", path: "scripts/server.sh"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "estoffelS"
    end
  end

  #Worker VM
  config.vm.define "estoffelSW" do |worker|
    worker.vm.network "private_network", type: "static", ip: "192.168.56.111"
    worker.vm.hostname = "estoffelSW"
    worker.vm.provision "shell", path: "scripts/common.sh"
    worker.vm.provision "shell", path: "scripts/worker.sh"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "estoffelSW"
    end
  end
end